/*
 * Example program to illustrate the use of the ECE 486 interface.
 * 
 * An input waveform is copied to the output DAC.  The waveform is also
 * squared and streamed to the second DAC output.  Each
 * USER button press inverts the signal on the original DAC.
 * 
 * The use of printf(), the pushbutton, and the LCD is also illustrated.
 */

#include "stm32l4xx_hal.h"
#include "stm32l476g_discovery.h"

#include "ece486.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "ece486_biquad.h"
#include "ece486_fir.h"

extern FlagStatus KeyPressed;   // Use to detect button presses

int main(void)
{
  int nsamp;
  float *input, *output1, *output2;
  static int button_count = 0;
  
	float bq_coef[] = {
		1, 1.618,1, -1.5371, 0.9025,
		1, -0.618, 1, 0.0, -0.81,
		1, 1.618,1, -1.5371, 0.9025,
		1, -0.618, 1, 0.0, -0.81,
		1, 1.618,1, -1.5371, 0.9025,
		1, -0.618, 1, 0.0, -0.81
	};

	float g = 1./6.6e04;

	//float fir_coef[20];
	//for(int i=0; i < 20; i++){
	//	fir_coef[i] = 1/20;
	//}


	float fir_coef[] = {
		1, .2, 1.2, -.3, .5,
		1, .2, -1, 1.3, -.4,
		.5, -.2, .5, 1.5, 1,
		1, 1, -.7, 1.3, .9
	};

	char lcd_str[8];

  /*
   * Set up ADCs, DACs, GPIO, Clocks, DMAs, and Timer
   * 
   * If your discovery board has been modified to support the external 
   * HSE reference, use the (better quality crystal controlled) HSE 
   * configuration.  If not, you can use the MSI reference, and things 
   * should still work -- but your clocks will drift over time.
   * 
   * The MSI (Medium speed internal) reference is the on-chip RC oscillator
   * 
   * The HSE (High speed external) reference is an external clock, either
   * provided through the external connector, or (if your board is modified)
   * from the crystal reference source generated by the other processor
   * on the development board.
   */
  // initialize_ece486(FS_50K, MONO_IN, STEREO_OUT, MSI_INTERNAL_RC);
  initialize_ece486(FS_48K, MONO_IN, STEREO_OUT, HSE_EXTERNAL_8MHz);
  
  /*
   * Allocate Required Memory
   *i
   */
  nsamp = getblocksize();
	
  input = (float *)malloc(sizeof(float)*nsamp);
  output1 = (float *)malloc(sizeof(float)*nsamp);
  output2 = (float *)malloc(sizeof(float)*nsamp);
  
  if (input==NULL || output1==NULL || output2==NULL) {
    flagerror(MEMORY_ALLOCATION_ERROR);
    while(1);
  }
  
  /*
   * Normally we avoid printf()... especially once we start actually 
   * processing streaming samples.  This is here to illustrate the 
   * use of printf for debugging programs.
   * 
   * To see the printf output, connect to the ST-Link serial port.
   * Use: 115200 8N1
   */
  // printf("Starting execution using %d samples per input block.\n",nsamp);
  
  /*
   * Infinite Loop to process the data stream, "nsamp" samples at a time
   */
	BIQUAD_T* biquad = init_biquad(6,g,bq_coef,nsamp);
	FIR_T* fir = init_fir(fir_coef,20,nsamp);

  while(1){
    /*
     * Ask for a block of ADC samples to be put into the working buffer
     *   getblock() will wait here until the input buffer is filled...  On return
     *   we work on the new data buffer... then return here to wait for 
     *   the next block
     */
    getblock(input);	

    /*
     * signal processing code to calculate the required output buffers
     */
    
    DIGITAL_IO_SET();	// Use a scope on PD0 to measure execution time
    DIGITAL_IO_RESET();	// (falling edge....  done processing data )
    
    /*
     * pass the processed working buffer back for DAC output
     */

		calc_fir(fir,input, output1);
		calc_biquad(biquad,input, output2);
		putblockstereo(output1,output2);

    if (KeyPressed) {
      KeyPressed = RESET;
      
      /*
       * On each press, modify the LCD display, and toggle an LED
       * (LED4=red, LED5=green) (Red is used to show error conditions)
       * 
       * Don't be surprised when these cause a Sample Overrun error, 
       * depending on your sample rate.
       */
      button_count++;
			char names[4][6] = {"aidan ", "caleb ", "sam   ", "tyler "};
      sprintf(lcd_str, "%s", names[button_count%4]);
      BSP_LCD_GLASS_DisplayString( (uint8_t *)lcd_str);
      BSP_LED_Toggle(LED5);
    }
  }
}

