#include "stm32l4xx_hal.h"
#include "stm32l476g_discovery.h"

#include "ece486.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "ece486_biquad.h"

extern FlagStatus KeyPressed;   // Use to detect button presses

int main(void)
{
  int nsamp;
  float *input, *output1;
  static int button_count = 0;
	
	// biquad coefficients
	float bq_coef[] = {
	0.138012, 0.223308, 0.138012, -0.200533, 0.640000, 
	0.216850, -0.412474, 0.216850, -1.090975, 0.792100, 
	1.213542, -1.963553, 1.213542, -1.085273, 0.810000, 
	0.865143, 1.017037, 0.865143, 0.059052, 0.883600 
	};

	// gain
	float g = .3572;

	char lcd_str[8];

  /*
   * Set up ADCs, DACs, GPIO, Clocks, DMAs, and Timer
   * 
   * If your discovery board has been modified to support the external 
   * HSE reference, use the (better quality crystal controlled) HSE 
   * configuration.  If not, you can use the MSI reference, and things 
   * should still work -- but your clocks will drift over time.
   * 
   * The MSI (Medium speed internal) reference is the on-chip RC oscillator
   * 
   * The HSE (High speed external) reference is an external clock, either
   * provided through the external connector, or (if your board is modified)
   * from the crystal reference source generated by the other processor
   * on the development board.
   */
  initialize_ece486(FS_48K, MONO_IN, MONO_OUT, HSE_EXTERNAL_8MHz);
 
	// set input blocksize 
  nsamp = getblocksize();

	// allocate required memory	
  input = (float *)malloc(sizeof(float)*nsamp);
  output1 = (float *)malloc(sizeof(float)*nsamp);
  
  if (input==NULL || output1==NULL) {
    flagerror(MEMORY_ALLOCATION_ERROR);
    while(1);
  }
 
	// Initialize biquad struct 
	BIQUAD_T* biquad = init_biquad(4,g,bq_coef,nsamp);

  /*
   * Infinite Loop to process the data stream, "nsamp" samples at a time
   */
  
	while(1){
    
		getblock(input);	

    DIGITAL_IO_SET();	// Use a scope on PD0 to measure execution time
    DIGITAL_IO_RESET();	// (falling edge....  done processing data )
    
		// calculate biquad output
		calc_biquad(biquad,input, output1);
		putblock(output1);

    if (KeyPressed) {
      KeyPressed = RESET;
      
      /*
       * On each press, modify the LCD display, and toggle an LED
       * (LED4=red, LED5=green) (Red is used to show error conditions)
       * 
       * Don't be surprised when these cause a Sample Overrun error, 
       * depending on your sample rate.
       */
      button_count++;
			char names[4][6] = {"aidan ", "caleb ", "sam   ", "tyler "};
      sprintf(lcd_str, "%s", names[button_count%4]);
      BSP_LCD_GLASS_DisplayString( (uint8_t *)lcd_str);
      BSP_LED_Toggle(LED5);
    }
  }
}
